sudo: required

language: javascript

services:
  - docker

script:
  - docker build -t foursball/foursball-api .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push foursball/foursball-api;
    fi
